name: Production Deployment (Node.js Server)

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: cd-production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: "production"
      url: ${{ vars.PROD_URL }}

    steps:
      - name: Deploy & Restart App on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd projects/trupper/backend

            echo "${{ secrets.PROD_ENV_FILE }}" | base64 -d > main.env

            git pull origin master

            npm ci --omit=dev

            pm2 restart app || pm2 start app.js trupper-backend app

            pm2 save
